### ISSUE TITLE
Issues with Chapter 5

### ISSUE THREAD

**Issue by CarlosLopez-Ciber** [PacktPublishing/Ethical-Hacking-techniques#1]
In this chapter, we are asked to install and download Ophcrack and LCP.  
I followed the download instructions as suggested in the Technical Requirements and attempted to install the mentioned programs on my Windows Metasploitable virtual machine. However, the Ophcrack program fails to install, and I encounter the error shown in the attached image:

![imagen](https://github.com/user-attachments/assets/5f1651bd-f3e5-466f-8e9c-f10b3cb43d9b)

**Comment by H3xxEdit** [comment]
This occurs when ophcrack attempts to download the rainbow tables and can't access the internet. I have already provided the tables for you. To resolve uncheck the "download and install...tables" during the ophcrack installation.

**Comment by H3xxEdit** [comment]
This is resolved

**Comment by CarlosLopez-Ciber** [comment]
I followed the procedures indicated in the book, however I kept getting an error message when opening the program. 

To solve the problem and to be able to develop the lab, I downloaded Ophcrack directly from your web page, however, I did it with the portable version.

https://ophcrack.sourceforge.io/download.php

Thank you very much for replying to the comment, it means a lot to me.

**Comment by H3xxEdit** [comment]
What is the error you are getting ? If it’s the URL error, just uncheck the download tables during the installation

From: Carlos Lopez ***@***.***>
Date: Wednesday, November 20, 2024 at 11:23 PM
To: PacktPublishing/Hands-On-Ethical-Hacking-Tactics ***@***.***>
Cc: H3xxEdit ***@***.***>, State change ***@***.***>
Subject: Re: [PacktPublishing/Hands-On-Ethical-Hacking-Tactics] Issues with Chapter 5 (Issue #1)

I followed the procedures indicated in the book, however I kept getting an error message when opening the program.

To solve the problem and to be able to develop the lab, I downloaded Ophcrack directly from your web page, however, I did it with the portable version.

https://ophcrack.sourceforge.io/download.php

Thank you very much for replying to the comment, it means a lot to me.

**Comment by CarlosLopez-Ciber** [comment]
Initially I received the error message in the URL, however, after unchecking the boxes and the program was installed, I received a missing msvcr71.dll message, so I decided to look for the program on the web and downloaded the portable and it worked.

**Comment by H3xxEdit** [comment]
Ok, after your initial post I checked and saw that error too. I have included the msvcr.dll in the folder now. If you place that in the same folder as the ophcrack that will fix that one.

Are you have any issues with the portable one ?

From: Carlos Lopez ***@***.***>
Date: Wednesday, November 20, 2024 at 11:34 PM
To: PacktPublishing/Hands-On-Ethical-Hacking-Tactics ***@***.***>
Cc: H3xxEdit ***@***.***>, State change ***@***.***>
Subject: Re: [PacktPublishing/Hands-On-Ethical-Hacking-Tactics] Issues with Chapter 5 (Issue #1)

Initially I received the error message in the URL, however, after unchecking the boxes and the program was installed, I received a missing msvcr71.dll message, so I decided to look for the program on the web and downloaded the portable and it worked.

**Comment by CarlosLopez-Ciber** [comment]
With the portable I have no problem, the program opened instantly.

**Comment by H3xxEdit** [comment]
Great, let me know if you run in to any other problems.

From: Carlos Lopez ***@***.***>
Date: Wednesday, November 20, 2024 at 11:45 PM
To: PacktPublishing/Hands-On-Ethical-Hacking-Tactics ***@***.***>
Cc: H3xxEdit ***@***.***>, State change ***@***.***>
Subject: Re: [PacktPublishing/Hands-On-Ethical-Hacking-Tactics] Issues with Chapter 5 (Issue #1)

With the portable I have no problem, the program opened instantly.
